name: hwr_env
channels:
- defaults
- anaconda
- conda-forge
- byu-handwriting-lab
dependencies:
- python=3.7.3
- pip=20.3.3
- tensorflow-gpu=2.3.0
- anaconda::numpy=1.19.1
- anaconda::pyyaml=5.3.1
- anaconda::pandas=1.1.3
- conda-forge::matplotlib=3.3.3
- anaconda::tqdm=4.50.2
- conda-forge::editdistance=0.5.3
- byu-handwriting-lab::word_beam_search=0.1
- pip:
 - tensorflow-addons==0.11.1
