package:
  name: hwr
  version: 0.1

source:
  path: ../

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python==3.7.3
    - tensorflow-gpu==2.3.0
    - numpy==1.19.1
    - pyyaml==5.3.1
    - pandas==1.1.3
    - matplotlib==3.3.3
    - tqdm==4.50.2
    - editdistance==0.5.3
    - word_beam_search==0.1
  run:
    - python==3.7.3
    - tensorflow-gpu==2.3.0
    - numpy==1.19.1
    - pyyaml==5.3.1
    - pandas==1.1.3
    - matplotlib==3.3.3
    - tqdm==4.50.2
    - editdistance==0.5.3
    - word_beam_search==0.1

test:
  imports:
    - hwr

about:
  home: https://github.com/BYU-Handwriting-Lab
